use chrono::Datelike;
use serde_json::Value;
use tauri::State;
use crate::{
    AppState,
    basiq::BasiqClient,
    db::{self, TxQuery},
    inference,
    mcp,
    models::{Holding, HardwareProfile, McpToolCall, Recommendation, Transaction},
};

// ── Transactions ──────────────────────────────────────────────────────────────

#[tauri::command]
pub async fn get_transactions(
    state: State<'_, AppState>,
    limit: Option<i64>,
    offset: Option<i64>,
    category: Option<String>,
) -> Result<Vec<Transaction>, String> {
    let conn = db::get_connection(&state.db_path).map_err(|e| e.to_string())?;
    let q = TxQuery {
        limit: limit.unwrap_or(200),
        offset: offset.unwrap_or(0),
        category: category.as_deref(),
        date_from: None,
        date_to: None,
        account_id: None,
    };
    db::query_transactions(&conn, &q).map_err(|e| e.to_string())
}

#[tauri::command]
pub async fn sync_transactions(
    state: State<'_, AppState>,
    api_key: String,
) -> Result<usize, String> {
    log::info!("Starting Basiq sync");

    let mut client = BasiqClient::new();
    client.authenticate(&api_key).map_err(|e| e.to_string())?;

    let raw_txns = client.fetch_transactions(24).map_err(|e| e.to_string())?;
    let accounts = client.list_accounts().map_err(|e| e.to_string())?;

    let account_names: std::collections::HashMap<String, String> = accounts.iter()
        .map(|a| (a.id.clone(), format!("{} — {}", a.institution_name, a.name)))
        .collect();

    let conn = db::get_connection(&state.db_path).map_err(|e| e.to_string())?;
    let mut count = 0;

    for raw in &raw_txns {
        let account_name = account_names.get(&raw.account.id)
            .cloned()
            .unwrap_or_else(|| raw.account.id.clone());

        if let Some(normalised) = crate::basiq::normalise(raw, &account_name) {
            let tx = Transaction {
                id: normalised.id,
                date: chrono::NaiveDate::from_ymd_opt(
                    normalised.post_date.year(),
                    normalised.post_date.month(),
                    normalised.post_date.day(),
                ).and_then(|d| d.and_hms_opt(0, 0, 0))
                 .map(|dt| chrono::DateTime::from_naive_utc_and_offset(dt, chrono::Utc))
                 .unwrap_or_default(),
                merchant_name: normalised.merchant_name,
                merchant_logo_url: normalised.merchant_logo_url,
                description: normalised.description,
                amount: normalised.amount_aud,
                running_balance: normalised.running_balance,
                category: normalised.category,
                subcategory: normalised.subcategory,
                account_id: normalised.account_id,
                account_name,
                tags: vec![],
                is_anomaly: false,
                anomaly_reason: None,
            };
            db::insert_transaction(&conn, &tx).map_err(|e| e.to_string())?;
            count += 1;
        }
    }

    log::info!("Sync complete: {} transactions stored", count);
    Ok(count)
}

// ── Holdings ──────────────────────────────────────────────────────────────────

#[tauri::command]
pub async fn get_holdings(
    _state: State<'_, AppState>,
) -> Result<Vec<Holding>, String> {
    // TODO: query holdings table + refresh prices from EODHD
    // For now returns empty — EODHD integration is Phase 4
    Ok(vec![])
}

// ── Recommendations ───────────────────────────────────────────────────────────

#[tauri::command]
pub async fn get_recommendations(
    _state: State<'_, AppState>,
) -> Result<Vec<Recommendation>, String> {
    // Recommendations are generated by the SLM and stored — return all pending
    // TODO: query recommendations table
    Ok(vec![])
}

// ── Chat / SLM ───────────────────────────────────────────────────────────────

#[tauri::command]
pub async fn send_chat_message(
    state: State<'_, AppState>,
    app: tauri::AppHandle,
    message: String,
    message_id: String,
    history: Vec<Value>,
) -> Result<(), String> {
    let system_prompt = build_system_prompt(&state).await;

    let mut messages = vec![serde_json::json!({
        "role": "system",
        "content": system_prompt,
    })];
    messages.extend(history);
    messages.push(serde_json::json!({
        "role": "user",
        "content": message,
    }));

    inference::stream_chat(
        state.inference.clone(),
        app,
        message_id,
        messages,
    );

    Ok(())
}

async fn build_system_prompt(state: &AppState) -> String {
    let conn = db::get_connection(&state.db_path).ok();
    let mut context_parts = vec![
        "You are a local personal finance assistant. All data stays on this device.".to_string(),
        "Back every numeric claim with an MCP tool call — never compute math yourself.".to_string(),
        "Available tools: query_transactions, aggregate, compare_periods, forecast, calculate, tax_estimate, plot.".to_string(),
    ];

    // Inject latest cashflow summary if DB available
    if let Some(conn) = conn {
        if let Ok(cashflow) = db::get_monthly_cashflow(&conn, 1) {
            if let Some((month, income, expenses)) = cashflow.last() {
                context_parts.push(format!(
                    "Recent context: {} — income ${:.0}, expenses ${:.0}, net ${:.0}.",
                    month, income, expenses, income - expenses
                ));
            }
        }
    }

    context_parts.join("\n")
}

// ── MCP Tools ─────────────────────────────────────────────────────────────────

#[tauri::command]
pub async fn run_mcp_tool(
    state: State<'_, AppState>,
    tool_name: String,
    args: Value,
) -> Result<McpToolCall, String> {
    mcp::dispatch(&tool_name, args, Some(&state.db_path)).map_err(|e| e.to_string())
}

// ── Hardware Detection ────────────────────────────────────────────────────────

#[tauri::command]
pub async fn detect_hardware() -> Result<HardwareProfile, String> {
    Ok(probe_hardware())
}

pub fn probe_hardware() -> HardwareProfile {
    use sysinfo::System;
    let mut sys = System::new();
    sys.refresh_memory();
    let ram_gb = sys.total_memory() / 1_073_741_824;

    // Try NVIDIA first via nvidia-smi
    if let Some((gpu_name, vram_gb)) = detect_nvidia() {
        let (backend, model_tier) = if vram_gb.unwrap_or(0.0) >= 6.0 {
            ("cuda".to_string(), "7B".to_string())
        } else {
            ("cuda".to_string(), "3B".to_string())
        };
        return HardwareProfile { backend, model_tier, gpu_name: Some(gpu_name), vram_gb, ram_gb };
    }

    // Try AMD / Vulkan via vulkaninfo
    if let Some(gpu_name) = detect_vulkan_gpu() {
        return HardwareProfile {
            backend: "vulkan".to_string(),
            model_tier: if ram_gb >= 16 { "7B".to_string() } else { "3B".to_string() },
            gpu_name: Some(gpu_name),
            vram_gb: None,
            ram_gb,
        };
    }

    // CPU fallback
    let model_tier = if ram_gb >= 12 { "7B" } else { "3B" }.to_string();
    HardwareProfile { backend: "cpu".to_string(), model_tier, gpu_name: None, vram_gb: None, ram_gb }
}

fn detect_nvidia() -> Option<(String, Option<f64>)> {
    let output = std::process::Command::new("nvidia-smi")
        .args(["--query-gpu=name,memory.total", "--format=csv,noheader,nounits"])
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let text = String::from_utf8_lossy(&output.stdout);
    let line = text.lines().next()?;
    let parts: Vec<&str> = line.splitn(2, ',').map(str::trim).collect();
    let name = parts.first()?.to_string();
    let vram_gb = parts.get(1).and_then(|s| s.parse::<f64>().ok()).map(|mb| mb / 1024.0);
    Some((name, vram_gb))
}

fn detect_vulkan_gpu() -> Option<String> {
    // Check for AMD on Linux via DRM
    #[cfg(target_os = "linux")]
    if std::path::Path::new("/dev/dri").exists() {
        if let Ok(entries) = std::fs::read_dir("/sys/bus/pci/devices") {
            for entry in entries.flatten() {
                let vendor_path = entry.path().join("vendor");
                if let Ok(vendor) = std::fs::read_to_string(&vendor_path) {
                    if vendor.trim() == "0x1002" {
                        // AMD GPU
                        let device_path = entry.path().join("device");
                        let device_id = std::fs::read_to_string(&device_path)
                            .unwrap_or_default();
                        return Some(format!("AMD GPU (device {})", device_id.trim()));
                    }
                }
            }
        }
    }
    None
}

// ── API Keys (OS credential vault) ───────────────────────────────────────────

#[tauri::command]
pub async fn save_api_keys(basiq_key: String, eodhd_key: String) -> Result<(), String> {
    store_credential("basiq", &basiq_key).map_err(|e| e.to_string())?;
    store_credential("eodhd", &eodhd_key).map_err(|e| e.to_string())?;
    Ok(())
}

#[tauri::command]
pub async fn get_api_keys() -> Result<Value, String> {
    let basiq = retrieve_credential("basiq").unwrap_or_default();
    let eodhd = retrieve_credential("eodhd").unwrap_or_default();
    Ok(serde_json::json!({
        "basiqApiKey": basiq,
        "eodhdApiKey": eodhd,
    }))
}

fn store_credential(service: &str, secret: &str) -> anyhow::Result<()> {
    if secret.is_empty() {
        return Ok(());
    }
    let entry = keyring::Entry::new("finance-copilot", service)?;
    entry.set_password(secret)?;
    Ok(())
}

fn retrieve_credential(service: &str) -> Option<String> {
    let entry = keyring::Entry::new("finance-copilot", service).ok()?;
    match entry.get_password() {
        Ok(p) => Some(p),
        Err(keyring::Error::NoEntry) => None,
        Err(e) => {
            log::warn!("keyring retrieval failed for {}: {}", service, e);
            None
        }
    }
}

// ── Data Wipe ─────────────────────────────────────────────────────────────────

#[tauri::command]
pub async fn wipe_all_data(state: State<'_, AppState>) -> Result<(), String> {
    log::warn!("Wiping all local data");
    let conn = db::get_connection(&state.db_path).map_err(|e| e.to_string())?;
    db::wipe_all_data(&conn).map_err(|e| e.to_string())?;

    // Clear keyring entries
    for service in &["basiq", "eodhd"] {
        if let Ok(entry) = keyring::Entry::new("finance-copilot", service) {
            let _ = entry.delete_password();
        }
    }

    Ok(())
}
